### ISSUE TITLE
Title and Intro for the ReadMe is missing.

### ISSUE THREAD

**Issue by praveenscience** [edusera-github/my-first-project#2]
Can someone please add the title and intro for the ReadMe on this repo?

**Comment by rohan-kulkarni-25** [comment]
Hey Praveen If any beginner want to take it let's give them a chance !! Else I am here to get it done !!

**Comment by koushikpuppala** [comment]
Hey, Praveen I will take it!

**Comment by Anushka-codergirl** [comment]
Hey! Praveen I would love to do it.

**Comment by vnmrsharma** [comment]
I would like to pick it !
