### ISSUE TITLE
Add Day 3 Contents.

### ISSUE THREAD

**Issue by praveenscience** [edusera-github/my-first-project#3]
Someone please add Day 3 contents.

**Comment by edusera-github** [comment]
I am picking this up.

**Comment by edusera-github** [comment]
Okay thanks, but I am the owner.

**Comment by setco-website** [comment]
Hey, can I pick this up? I am not you or I am not the owner of this repo! 😁

**Comment by setco-website** [comment]
Okay cool, I'll start working on this issue right away.
